filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
repositories:
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: dev
  url: http://bucketrepo/bucketrepo/charts
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.12
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - charts/jenkins-x/jxboot-helmfile-resources/values.yaml
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: jx3/jenkins-x-crds
  version: 1.0.7
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
- chart: cdf/tekton-pipeline
  version: 0.17.1
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
- chart: jx3/jx-pipelines-visualizer
  version: 0.0.51
  name: jx-pipelines-visualizer
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
- chart: jx3/jx-preview
  version: 0.0.114
  name: jx-preview
  namespace: jx
- chart: jenkins-x/lighthouse
  version: 0.0.869
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/bucketrepo
  version: 0.1.39
  name: bucketrepo
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/bucketrepo/values.yaml.gotmpl
- chart: jx3/jx-build-controller
  version: 0.0.14
  name: jx-build-controller
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
- chart: dev/nodey539
  version: 1.0.0
  name: nodey539
  namespace: jx-staging
templates: {}
missingFileHandler: ""
