apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        jstrachan/jx3-openshift-local: true
        jstrachan/nodey538: true
        jstrachan/nodey539: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx3-openshift-local: merge
        jstrachan/nodey538: merge
        jstrachan/nodey539: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-openshift-local
        - jstrachan/nodey538
        - jstrachan/nodey539
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-openshift-local
        - jstrachan/nodey538
        - jstrachan/nodey539
      target_url: http://dashboard-jx.apps-crc.testing
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
